#!/usr/bin/bash

__menu="
Available browsers:
1. Brave
2. Chrome
3. Chromium
4. Firefox
5. Floorp
"

browserbox() {
  blink_fixes=0
  wayland_fixes=0

  for arg in "$@"; do
    case "$arg" in
      -w | --wayland)
        wayland_fixes=1
        ;;
      *)
        BROWSER="$arg"
        ;;
    esac
  done

  if [[ -z "$BROWSER" ]]; then
    echo "$__menu"
    read -p "Select browser: " BROWSER
  fi

  BROWSER=$(echo "$BROWSER" | awk '{print tolower($0)}')

  case "$BROWSER" in
    1 | brave)
      IMAGE_NAME="bravebox"
      BROWSER_NAME="brave-browser"
      blink_fixes="1"
      ;;
    2 | chrome)
      IMAGE_NAME="chromebox"
      BROWSER_NAME="chrome-browser"
      blink_fixes="1"
      ;;
    3 | chromium)
      IMAGE_NAME="chromiumbox"
      BROWSER_NAME="chromium-browser"
      blink_fixes="1"
      ;;
    4 | firefox)
      IMAGE_NAME="firebox"
      BROWSER_NAME="firefox"
      ;;
    5 | floorp)
      IMAGE_NAME="floorpbox"
      BROWSER_NAME="floorp"
      ;;
    *)
      echo "Invalid option selected. Opening menu..."
      browserbox
      ;;
  esac
  distrobox create -i ghcr.io/eyecantcu/"$IMAGE_NAME" -n "$IMAGE_NAME" --yes --nvidia

  DESKTOP_PATH="~/.local/share/applications"
  DESKTOP_FILE="$DESKTOP_PATH"/"$IMAGE_NAME"-"$BROWSER_NAME".desktop

  if [[ "$blink_fixes" -eq "1" && "$wayland_fixes" -eq "1" ]]; then
    distrobox enter -n "$IMAGE_NAME" -- 'bash -c "sudo locale-gen && distrbox-export --app $BROWSER --extra-flags \"--ozone-platform=wayland --disable-features=WaylandFractionalScaleV1\""'
    sed -i 's/ \/bin\/sh -l -c //' "$DESKTOP_FILE"
  else
    distrobox enter -n "$IMAGE_NAME" -- 'bash -c "sudo locale-gen && distrbox-export --app $BROWSER"'
  fi

  if [[ "$wayland_fixes" -eq "1" ]]; then
    TARGET_DESKTOP_FILE="$DESKTOP_PATH"/"$BROWSER_NAME".desktop
    mv "$DESKTOP_FILE" "$TARGET_DESKTOP_FILE"
    DESKTOP_FILE="$TARGET_DESKTOP_FILE"
  fi

  xdg-settings set default-web-browser "$DESKTOP_FILE"
}
browserbox "$@"
